//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BiometricoWeb.SapServiceC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_HR_CONS_CAPAC_INF2", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_HR_CONS_CAPAC_INF2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZMF_HR_CONS_CAPAC_INF2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_HR_CONS_CAPAC_INF2() {
            this.Url = global::BiometricoWeb.Properties.Settings.Default.BiometricoWeb_SapServiceC_ZWS_HR_CONS_CAPAC_INF2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZMF_HR_CONS_CAPAC_INF2CompletedEventHandler ZMF_HR_CONS_CAPAC_INF2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_HR_CONS_CAPAC_INF2:ZMF_HR_CONS_CAPAC_I" +
            "NF2Request", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZMF_HR_CONS_CAPAC_INF2Response", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZMF_HR_CONS_CAPAC_INF2Response ZMF_HR_CONS_CAPAC_INF2([System.Xml.Serialization.XmlElementAttribute("ZMF_HR_CONS_CAPAC_INF2", Namespace="urn:sap-com:document:sap:rfc:functions")] ZMF_HR_CONS_CAPAC_INF2 ZMF_HR_CONS_CAPAC_INF21) {
            object[] results = this.Invoke("ZMF_HR_CONS_CAPAC_INF2", new object[] {
                        ZMF_HR_CONS_CAPAC_INF21});
            return ((ZMF_HR_CONS_CAPAC_INF2Response)(results[0]));
        }
        
        /// <remarks/>
        public void ZMF_HR_CONS_CAPAC_INF2Async(ZMF_HR_CONS_CAPAC_INF2 ZMF_HR_CONS_CAPAC_INF21) {
            this.ZMF_HR_CONS_CAPAC_INF2Async(ZMF_HR_CONS_CAPAC_INF21, null);
        }
        
        /// <remarks/>
        public void ZMF_HR_CONS_CAPAC_INF2Async(ZMF_HR_CONS_CAPAC_INF2 ZMF_HR_CONS_CAPAC_INF21, object userState) {
            if ((this.ZMF_HR_CONS_CAPAC_INF2OperationCompleted == null)) {
                this.ZMF_HR_CONS_CAPAC_INF2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZMF_HR_CONS_CAPAC_INF2OperationCompleted);
            }
            this.InvokeAsync("ZMF_HR_CONS_CAPAC_INF2", new object[] {
                        ZMF_HR_CONS_CAPAC_INF21}, this.ZMF_HR_CONS_CAPAC_INF2OperationCompleted, userState);
        }
        
        private void OnZMF_HR_CONS_CAPAC_INF2OperationCompleted(object arg) {
            if ((this.ZMF_HR_CONS_CAPAC_INF2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZMF_HR_CONS_CAPAC_INF2Completed(this, new ZMF_HR_CONS_CAPAC_INF2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMF_HR_CONS_CAPAC_INF2 {
        
        private string cIEVEField;
        
        private string cONSUField;
        
        private string cONTAField;
        
        private string dICONField;
        
        private string dOMI1Field;
        
        private string dOMI2Field;
        
        private string fCONSField;
        
        private string fEVENField;
        
        private string lUEVEField;
        
        private string pAISField;
        
        private string pASAPField;
        
        private string pERNRField;
        
        private string rTNField;
        
        private string sEMINField;
        
        private string tELEFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CIEVE {
            get {
                return this.cIEVEField;
            }
            set {
                this.cIEVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONSU {
            get {
                return this.cONSUField;
            }
            set {
                this.cONSUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CONTA {
            get {
                return this.cONTAField;
            }
            set {
                this.cONTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DICON {
            get {
                return this.dICONField;
            }
            set {
                this.dICONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOMI1 {
            get {
                return this.dOMI1Field;
            }
            set {
                this.dOMI1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOMI2 {
            get {
                return this.dOMI2Field;
            }
            set {
                this.dOMI2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FCONS {
            get {
                return this.fCONSField;
            }
            set {
                this.fCONSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FEVEN {
            get {
                return this.fEVENField;
            }
            set {
                this.fEVENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LUEVE {
            get {
                return this.lUEVEField;
            }
            set {
                this.lUEVEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PAIS {
            get {
                return this.pAISField;
            }
            set {
                this.pAISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PASAP {
            get {
                return this.pASAPField;
            }
            set {
                this.pASAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RTN {
            get {
                return this.rTNField;
            }
            set {
                this.rTNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SEMIN {
            get {
                return this.sEMINField;
            }
            set {
                this.sEMINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELEF {
            get {
                return this.tELEFField;
            }
            set {
                this.tELEFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMF_HR_CONS_CAPAC_INF2Response {
        
        private string mSJField;
        
        private byte[] pDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSJ {
            get {
                return this.mSJField;
            }
            set {
                this.mSJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] PDF {
            get {
                return this.pDFField;
            }
            set {
                this.pDFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ZMF_HR_CONS_CAPAC_INF2CompletedEventHandler(object sender, ZMF_HR_CONS_CAPAC_INF2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZMF_HR_CONS_CAPAC_INF2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZMF_HR_CONS_CAPAC_INF2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZMF_HR_CONS_CAPAC_INF2Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZMF_HR_CONS_CAPAC_INF2Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591