//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BiometricoWeb.SapServicesH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_HR_VACACIONES", Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZWS_HR_VACACIONES : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZFM_CONSULTA_VACACIONESOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_HR_VACACIONES() {
            this.Url = global::BiometricoWeb.Properties.Settings.Default.BiometricoWeb_SapServicesH_ZWS_HR_VACACIONES;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZFM_CONSULTA_VACACIONESCompletedEventHandler ZFM_CONSULTA_VACACIONESCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_HR_Vacaciones:ZFM_CONSULTA_VACACIONESR" +
            "equest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ZFM_CONSULTA_VACACIONESResponse", Namespace="urn:sap-com:document:sap:rfc:functions")]
        public ZFM_CONSULTA_VACACIONESResponse ZFM_CONSULTA_VACACIONES([System.Xml.Serialization.XmlElementAttribute("ZFM_CONSULTA_VACACIONES", Namespace="urn:sap-com:document:sap:rfc:functions")] ZFM_CONSULTA_VACACIONES ZFM_CONSULTA_VACACIONES1) {
            object[] results = this.Invoke("ZFM_CONSULTA_VACACIONES", new object[] {
                        ZFM_CONSULTA_VACACIONES1});
            return ((ZFM_CONSULTA_VACACIONESResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ZFM_CONSULTA_VACACIONESAsync(ZFM_CONSULTA_VACACIONES ZFM_CONSULTA_VACACIONES1) {
            this.ZFM_CONSULTA_VACACIONESAsync(ZFM_CONSULTA_VACACIONES1, null);
        }
        
        /// <remarks/>
        public void ZFM_CONSULTA_VACACIONESAsync(ZFM_CONSULTA_VACACIONES ZFM_CONSULTA_VACACIONES1, object userState) {
            if ((this.ZFM_CONSULTA_VACACIONESOperationCompleted == null)) {
                this.ZFM_CONSULTA_VACACIONESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZFM_CONSULTA_VACACIONESOperationCompleted);
            }
            this.InvokeAsync("ZFM_CONSULTA_VACACIONES", new object[] {
                        ZFM_CONSULTA_VACACIONES1}, this.ZFM_CONSULTA_VACACIONESOperationCompleted, userState);
        }
        
        private void OnZFM_CONSULTA_VACACIONESOperationCompleted(object arg) {
            if ((this.ZFM_CONSULTA_VACACIONESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZFM_CONSULTA_VACACIONESCompleted(this, new ZFM_CONSULTA_VACACIONESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_CONSULTA_VACACIONES {
        
        private string p_BEGDAField;
        
        private string p_BUKRSField;
        
        private string p_ENDDAField;
        
        private string p_PERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_BEGDA {
            get {
                return this.p_BEGDAField;
            }
            set {
                this.p_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_BUKRS {
            get {
                return this.p_BUKRSField;
            }
            set {
                this.p_BUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_ENDDA {
            get {
                return this.p_ENDDAField;
            }
            set {
                this.p_ENDDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string P_PERNR {
            get {
                return this.p_PERNRField;
            }
            set {
                this.p_PERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_CONSULTA_VACACIONESResponse {
        
        private decimal p_DIASField;
        
        private short p_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal P_DIAS {
            get {
                return this.p_DIASField;
            }
            set {
                this.p_DIASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short P_RESULT {
            get {
                return this.p_RESULTField;
            }
            set {
                this.p_RESULTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ZFM_CONSULTA_VACACIONESCompletedEventHandler(object sender, ZFM_CONSULTA_VACACIONESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZFM_CONSULTA_VACACIONESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZFM_CONSULTA_VACACIONESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZFM_CONSULTA_VACACIONESResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZFM_CONSULTA_VACACIONESResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591